services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/project
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_PASSWORD: 1
